### PR TITLE
Prtr 2020

### PR DESCRIPTION
**Pull request by AnnaZagorski**
Hi Kevin, hi Christian,
This is an analysis of PRTR data for 2018, 2019, and 2020. I added some graphs, adjusted the quantiles, and added Excel files in the output. Please look over it.

### CODE REVIEW

**Comment by kevin-hausmann** [comment]
If saw these kind of problems running the notebook on CODE-DE:

image

I could kind of fix it by changing `%matplotlib notebook` to `%matplotlib inline` in cell 2 - do you know why this happens?

**Comment by kevin-hausmann** [comment]
There is also this point source not mapped to any stack height, could you please fix that (maybe with help from @Christian-Mielke)?

image

**Comment by kevin-hausmann** [comment]
Finally, I noted that "Umlauts" are pushed to the bottom of this list, can we use a German sorting collation to fix that?

image

**Comment by kevin-hausmann** [comment]
Other than that this looks like great work, thanks!

**Comment by AnnaZagorski** [comment]
> If saw these kind of problems running the notebook on CODE-DE:
> 
> image
> 
> I could kind of fix it by changing `%matplotlib notebook` to `%matplotlib inline` in cell 2 - do you know why this happens?

I don't know why the error happens, in CODE-DE you can rather use %matplotlib inline then

**Comment by AnnaZagorski** [comment]
> There is also this point source not mapped to any stack height, could you please fix that (maybe with help from @Christian-Mielke)?
> 
> image

This point source is deleted in section 8 anyway, because this point source does not contain a single emission (in the 2019 and 2020 datasets). Therefore, it is not necessary to map it. Or what do you think?

**Comment by AnnaZagorski** [comment]
Hello you two, I have worked through all of Kevin's comments and created a new commit. I hope it all fits now so.

**Comment by kevin-hausmann** [comment]
> > There is also this point source not mapped to any stack height, could you please fix that (maybe with help from @Christian-Mielke)?
> > image
> 
> This point source is deleted in section 8 anyway, because this point source does not contain a single emission (in the 2019 and 2020 datasets). Therefore, it is not necessary to map it. Or what do you think?

I think it would be good to fix it because I simply pressed "Run all cells" and it didn't since this error was thrown. Thanks!

**Review by Christian-Mielke — APPROVED** [review]

**Comment by AnnaZagorski** [comment]
> > > If saw these kind of problems running the notebook on CODE-DE:
> > > image
> > > I could kind of fix it by changing `%matplotlib notebook` to `%matplotlib inline` in cell 2 - do you know why this happens?
> > 
> > 
> > I don't know why the error happens, in CODE-DE you can rather use %matplotlib inline then
> 
> Okay, that fine. Maybe you include a comment on the first use to alert future me? You do not have to change anything beyond that...

Okay, I left a comment that you can't use "%matplotlib notebook" in CODE-DE but "%matplotlib inline"

**Comment by AnnaZagorski** [comment]
> > > There is also this point source not mapped to any stack height, could you please fix that (maybe with help from @Christian-Mielke)?
> > > image
> > 
> > 
> > This point source is deleted in section 8 anyway, because this point source does not contain a single emission (in the 2019 and 2020 datasets). Therefore, it is not necessary to map it. Or what do you think?
> 
> I think it would be good to fix it because I simply pressed "Run all cells" and it didn't since this error was thrown. Thanks!

Okay, I fixed it (a detailed explanation will be sent by email). Now, everything is working.

**Review by kevin-hausmann — APPROVED** [review]
This all looks fine now - thanks!

**Pull request merged**
